### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by pandamal0** [dd-hebert/agilent-uvvis-to-csv#4]
Hi I talked to you a while ago about other of this errors, and it's happening again with a teacher's file that I'm converting.

So the error was UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 1: ordinal not in range(128)

I will send the data that wasn't working with one that works (chlorphyll), sorry to bother again.
[srry.zip](https://github.com/dd-hebert/agilent-uvvis-to-csv/files/14104720/srry.zip)

**Comment by dd-hebert** [comment]
Hi pandamal!

No worries, it's not a bother. I will take a look when I get some time in the next few days. The problem is caused by an unexpected character somewhere in the data, it should (hopefully) be an easy and quick fix. 

Best,
-DDH

**Comment by dd-hebert** [comment]
Hi pandamal,

I've released a fix for the script. The error was caused by a "Ó" character in some of the sample names. I've added a quick fix for handling extended ascii characters (they get replaced with "�"). I'll try and come up with a more elegant solution in the near future. The script should convert your teacher's files now.

-DDH
